# Generated by Django 4.2.5 on 2023-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=200, unique=True, verbose_name='Уникальный идентификатор новости')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Прямая ссылка на новость')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок новости')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации новости')),
                ('text', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Полный текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
